//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace subway.ResxResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_cn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_cn() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("subway.ResxResources.zh-cn", typeof(zh_cn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 1号线 的本地化字符串。
        /// </summary>
        internal static string button_1LineMap {
            get {
                return ResourceManager.GetString("button_1LineMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2号线 的本地化字符串。
        /// </summary>
        internal static string button_2LineMap {
            get {
                return ResourceManager.GetString("button_2LineMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string button_back {
            get {
                return ResourceManager.GetString("button_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中文 的本地化字符串。
        /// </summary>
        internal static string button_changeLanguage {
            get {
                return ResourceManager.GetString("button_changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快捷购票 的本地化字符串。
        /// </summary>
        internal static string button_fastTicket {
            get {
                return ResourceManager.GetString("button_fastTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总图 的本地化字符串。
        /// </summary>
        internal static string button_fullMap {
            get {
                return ResourceManager.GetString("button_fullMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1张 的本地化字符串。
        /// </summary>
        internal static string button_Number_1 {
            get {
                return ResourceManager.GetString("button_Number_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2张 的本地化字符串。
        /// </summary>
        internal static string button_Number_2 {
            get {
                return ResourceManager.GetString("button_Number_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3张 的本地化字符串。
        /// </summary>
        internal static string button_Number_3 {
            get {
                return ResourceManager.GetString("button_Number_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4张 的本地化字符串。
        /// </summary>
        internal static string button_Number_4 {
            get {
                return ResourceManager.GetString("button_Number_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 5张 的本地化字符串。
        /// </summary>
        internal static string button_Number_5 {
            get {
                return ResourceManager.GetString("button_Number_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 6张 的本地化字符串。
        /// </summary>
        internal static string button_Number_6 {
            get {
                return ResourceManager.GetString("button_Number_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7张 的本地化字符串。
        /// </summary>
        internal static string button_Number_7 {
            get {
                return ResourceManager.GetString("button_Number_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8张 的本地化字符串。
        /// </summary>
        internal static string button_Number_8 {
            get {
                return ResourceManager.GetString("button_Number_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买 的本地化字符串。
        /// </summary>
        internal static string button_OkToPay {
            get {
                return ResourceManager.GetString("button_OkToPay", resourceCulture);
            }
        }
    }
}
